### ISSUE TITLE
question about the commend "refine"

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#163]
Hello @s9roll7 

when doing the img2img generation, it is quite difficult to generate larger size even for 640x640 because hardware not good enougn with many frame to generate (4080 12G laptop) with about 300+ frames.

and I notice that there is a "refine" commend but not sure how it's work,

can you please help to do a little explain on this commend?  question as below:
if I generation imgs for maybe 384x384, and then I use refine to 768x768
1.1 is the quality of image will be better than I generation 512x512 and use SD to upscale it (by SD upscale, it alwaus cause some flashing when combining as video)
1.2 if I generate smaller imgs (says 384x384) and use refine commend to upscale to 768x768, does it take less vram than generate 786 diredcly? which means I can run by less vram (12G) machine to generate larger and better quality imgs?

thanks!

**Comment by hylarucoder** [comment]
Based on my experience (correct me if i'm wrong):

> 1.1 is the quality of image will be better than I generation 512x512 and use SD to upscale it (by SD upscale, it alwaus cause some flashing when combining as video)

The 'refine' command doesn't necessarily improve the quality compared to the 'upscale' command (there might be some misconfigurations on my part), but it does generally result in smoother videos with less flickering.

> 1.2 if I generate smaller imgs (says 384x384) and use refine commend to upscale to 768x768, does it take less vram than generate 786 diredcly? which means I can run by less vram (12G) machine to generate larger and better quality imgs?

No, but the VRAM usage is almost the same. When the interpolation_multiplier is set to 1, the 'refine' command is `generates` images using a tile-based control network, and then applies the "RIFE FFmpeg configuration".

It's essentially the same process. `You can create a new folder and place the tile image into it. then run generate and then run  ffmpeg with rife setting`

PS: With a 4060Ti 16GB graphics card, I am able to set the maximum parameters for the 'refine' command to -W 768 -C 8 (height:1000). These parameters strike a balance between VRAM usage and processing speed, which is crucial because maxing out VRAM can significantly slow down the generation process.

**Comment by s9roll7** [comment]
In the stylize command,
W512 H512 L128 C16 for generating, and
W768 H768 L128 C8 for upscaling.

How about reducing context?

**Comment by s9roll7** [comment]
I've revised the memory usage in the latest version, so it's probably better.
